# -*- coding: utf-8 -*-
"""
OZI — данные центров (сгенерировано из OZI_База_v1, 134 реальных центра).
Слой данных изолирован: чтобы перейти на Google Sheets, заменяется только load_centers().
Все данные реальные (выгрузка 2ГИS/Google). Демо-центров нет.
"""

CATEGORIES = {
    "academic":    "🎓 Академическое и языки",
    "mind":        "🧠 Ум и логика",
    "art":         "🎨 Творчество",
    "sport":       "🤸 Спорт",
    "combat":      "🥋 Единоборства",
    "development": "🌱 Развитие ребёнка",
}

DISTRICTS = {
    "esil":     "🏙 Есиль",
    "almaty":   "🏘 Алматинский",
    "saryarka": "🏗 Сарыарка/Байконур",
    "nura":     "🌿 Нура/Есиль-запад",
    "any":      "🗺 Любой район",
}

AGE_GROUPS = {
    "4-6":   (4, 6,  "👶 4–6 лет"),
    "7-10":  (7, 10, "🧒 7–10 лет"),
    "11-14": (11, 14, "👦 11–14 лет"),
    "15+":   (15, 18, "🧑 15+ лет"),
    "any":   (0, 99, "🎂 Любой возраст"),
}

BUDGETS = {
    "low":    (0,     15000,  "💚 до 15 000 ₸"),
    "medium": (15001, 25000,  "💛 15–25 тыс ₸"),
    "high":   (25001, 40000,  "🟠 25–40 тыс ₸"),
    "any":    (0,     10**9,  "💜 Любой бюджет"),
}

CENTERS = [
  {
    "id": 1,
    "name": "Kinderly — Детский центр развития (левый берег)",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "nura",
    "dist_label": "Нура/Есиль-запад",
    "address": "Айтеке би 16",
    "phone": "+7 700 725 3535",
    "whatsapp": "+7 700 725 3535",
    "instagram": "",
    "rating": 5.0,
    "reviews": 9,
    "schedule": "Пн–Пт 9–18, Сб–Вс 9–17",
    "lat": 51.1426,
    "lon": 71.3832,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 2,
    "name": "Детский центр развития «Бемби»",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "просп. Абая 28",
    "phone": "+7 701 609 2552",
    "whatsapp": "+7 701 609 2552",
    "instagram": "",
    "rating": 4.9,
    "reviews": 29,
    "schedule": "Пн–Пт 8:30–19, Сб 10–15",
    "lat": 51.1683,
    "lon": 71.4277,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 3,
    "name": "Super Deti",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Гейдара Алиева 9",
    "phone": "+7 701 202 3456",
    "whatsapp": "+7 701 202 3456",
    "instagram": "",
    "rating": None,
    "reviews": None,
    "schedule": "Пн–Пт 9–18",
    "lat": 51.1166,
    "lon": 71.4176,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 4,
    "name": "Uniqkids",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Куйши Дина 14",
    "phone": "+7 747 202 0855",
    "whatsapp": "+7 747 202 0855",
    "instagram": "",
    "rating": 3.0,
    "reviews": 4,
    "schedule": "Пн–Пт 9–18:30",
    "lat": 51.1459,
    "lon": 71.4719,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 5,
    "name": "Подготовка к школе (Ташенова 27)",
    "cat_key": "academic",
    "cat_label": "🎓 Академическое и языки",
    "subcat": "Подготовка к школе",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Ж. Ташенова 27, оф. 411",
    "phone": "+7 702 815 0590",
    "whatsapp": "+7 702 815 0590",
    "instagram": "",
    "rating": None,
    "reviews": None,
    "schedule": "Ежедневно 9–21",
    "lat": 51.1546,
    "lon": 71.4512,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 6,
    "name": "«Талант» балалар дамыту орталығы",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Кенесары 45",
    "phone": "+7 775 702 1109",
    "whatsapp": "+7 775 702 1109",
    "instagram": "",
    "rating": 4.5,
    "reviews": 13,
    "schedule": "Пн–Пт 8:30–20, Сб 9–19, Вс 9–15",
    "lat": 51.1665,
    "lon": 71.4295,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 7,
    "name": "Kid's Time — центр развития",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Байтурсынова 19",
    "phone": "+7 777 863 9911",
    "whatsapp": "+7 777 863 9911",
    "instagram": "",
    "rating": 5.0,
    "reviews": 8,
    "schedule": "Пн–Пт 8–20",
    "lat": 51.1238,
    "lon": 71.4762,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 8,
    "name": "Start School — детский центр развития",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Жанибек Тархана 17",
    "phone": "+7 777 880 6000",
    "whatsapp": "+7 777 880 6000",
    "instagram": "",
    "rating": 5.0,
    "reviews": 6,
    "schedule": "Пн–Пт 8–19",
    "lat": 51.1592,
    "lon": 71.4565,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 9,
    "name": "Центр развития «Harmony»",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Куйши Дина 8",
    "phone": "+7 771 103 5289",
    "whatsapp": "+7 771 103 5289",
    "instagram": "",
    "rating": 5.0,
    "reviews": 10,
    "schedule": "Пн–Пт 9–19, Сб 9–16",
    "lat": 51.1537,
    "lon": 71.4874,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 10,
    "name": "Центр развития ABC",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. А. Янушкевича 1",
    "phone": "+7 705 100 5725",
    "whatsapp": "+7 705 100 5725",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "Пн–Пт 9–20",
    "lat": 51.1588,
    "lon": 71.4608,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 11,
    "name": "Оранжевый мир — детский образовательный центр",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "р-н Есиль (4C8H+459)",
    "phone": "+7 701 255 1678",
    "whatsapp": "+7 701 255 1678",
    "instagram": "",
    "rating": None,
    "reviews": None,
    "schedule": "Пн–Сб 9–19",
    "lat": 51.1153,
    "lon": 71.428,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 12,
    "name": "Счастливая семья",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Тауелсиздик 21/6",
    "phone": "+7 777 761 7508",
    "whatsapp": "+7 777 761 7508",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "Пн–Пт 9–21, Сб–Вс 10–17",
    "lat": 51.1463,
    "lon": 71.4571,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 13,
    "name": "MultiKids",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Тауелсиздик 6/3",
    "phone": "+7 702 626 3666",
    "whatsapp": "+7 702 626 3666",
    "instagram": "",
    "rating": 1.0,
    "reviews": 1,
    "schedule": "Пн–Пт 9–18",
    "lat": 51.1501,
    "lon": 71.4609,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 14,
    "name": "Страна Умельцев — центр развития и творчества",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Творчество",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "р-н Алматинский (4FWM+RFW)",
    "phone": "",
    "whatsapp": "",
    "instagram": "",
    "rating": 5.0,
    "reviews": 14,
    "schedule": "Пн–Пт 10–18",
    "lat": 51.1471,
    "lon": 71.4837,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 15,
    "name": "Школа скорочтения Инны Каулиной (Kinna)",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Скорочтение / Ментальная арифметика",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Ж. Ташенова 17",
    "phone": "+7 708 425 5000",
    "whatsapp": "+7 708 425 5000",
    "instagram": "",
    "rating": 4.0,
    "reviews": 8,
    "schedule": "Пн–Сб",
    "lat": 51.1527,
    "lon": 71.4458,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 16,
    "name": "«Akyldy Bala» — скорочтение, каллиграфия, ментальная арифметика",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Скорочтение / Ментальная арифметика",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Майлина 19, БЦ Таймас, каб. 422А",
    "phone": "+7 702 846 8169",
    "whatsapp": "+7 702 846 8169",
    "instagram": "",
    "rating": 5.0,
    "reviews": 13,
    "schedule": "Пн–Пт 9–19, Сб 10–16:30",
    "lat": 51.1462,
    "lon": 71.4796,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 17,
    "name": "INTELLIZY CENTER",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Кабанбай батыра 48/1, ЖК Времена года",
    "phone": "+7 702 703 7636",
    "whatsapp": "+7 702 703 7636",
    "instagram": "",
    "rating": 3.0,
    "reviews": 2,
    "schedule": "Ежедневно 9–18",
    "lat": 51.1051,
    "lon": 71.4057,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 18,
    "name": "Академия шахмат Динары Садуакасовой (левый берег)",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Шахматы",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Гейдара Алиева 9",
    "phone": "+7 702 541 5151",
    "whatsapp": "+7 702 541 5151",
    "instagram": "",
    "rating": 5.0,
    "reviews": 4,
    "schedule": "Вт–Вс",
    "lat": 51.1166,
    "lon": 71.4176,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 19,
    "name": "Академия шахмат Динары Садуакасовой (Тауелсиздик)",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Шахматы",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Тауелсиздик 52",
    "phone": "+7 700 541 5151",
    "whatsapp": "+7 700 541 5151",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "Вт–Вс",
    "lat": 51.1207,
    "lon": 71.472,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 20,
    "name": "Академия шахмат Grandmaster (Улы Дала)",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Шахматы",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Улы Дала 65/2",
    "phone": "+7 702 728 3711",
    "whatsapp": "+7 702 728 3711",
    "instagram": "",
    "rating": 5.0,
    "reviews": 4,
    "schedule": "Пн–Пт 10–19, Вс 10–19",
    "lat": 51.0953,
    "lon": 71.4282,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 21,
    "name": "Академия шахмат Grandmaster (ул. 22-4)",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Шахматы",
    "dist_key": "nura",
    "dist_label": "Нура/Есиль-запад",
    "address": "ул. 22-4, д. 3",
    "phone": "+7 702 728 3711",
    "whatsapp": "+7 702 728 3711",
    "instagram": "",
    "rating": 4.3,
    "reviews": 6,
    "schedule": "Ежедневно",
    "lat": 51.144,
    "lon": 71.3822,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 22,
    "name": "Шахматная школа «Маэстро»",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Шахматы",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Сыганак 14/1",
    "phone": "+7 705 665 3132",
    "whatsapp": "+7 705 665 3132",
    "instagram": "",
    "rating": 5.0,
    "reviews": 4,
    "schedule": "Ежедневно 9–20",
    "lat": 51.1214,
    "lon": 71.4336,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 23,
    "name": "Центральный шахматный клуб «Астана»",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Шахматы",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Асанкайгы 2",
    "phone": "+7 771 046 4777",
    "whatsapp": "+7 771 046 4777",
    "instagram": "",
    "rating": 4.1,
    "reviews": 11,
    "schedule": "Ежедневно 9–20",
    "lat": 51.1631,
    "lon": 71.4438,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 24,
    "name": "Школа шахмат Smart Step",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Шахматы",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Д. Конаева 14Б, оф. 387",
    "phone": "+7 702 554 7457",
    "whatsapp": "+7 702 554 7457",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "Пн–Пт 10–18, Сб 11–16",
    "lat": 51.1289,
    "lon": 71.4335,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 25,
    "name": "Академия шахмат «Национальный союз шахматистов»",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Шахматы",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Кенесары 65",
    "phone": "+7 7172 46 47 77",
    "whatsapp": "+7 7172 46 47 77",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "Ежедневно 9–20",
    "lat": 51.1675,
    "lon": 71.4406,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 26,
    "name": "Школа шахмат Chess School",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Шахматы",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "просп. Сарыарка 17, оф. 39",
    "phone": "+7 701 888 1446",
    "whatsapp": "+7 701 888 1446",
    "instagram": "",
    "rating": 5.0,
    "reviews": 64,
    "schedule": "Пн–Пт 10–20, Сб 10–13, Вс 11–15",
    "lat": 51.1682,
    "lon": 71.4078,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 27,
    "name": "Школа шахмат «Ход Конём»",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Шахматы",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "ул. Бейбитшилик 54",
    "phone": "+7 700 836 8184",
    "whatsapp": "+7 700 836 8184",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "Ежедневно",
    "lat": 51.1843,
    "lon": 71.4167,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 28,
    "name": "English House",
    "cat_key": "academic",
    "cat_label": "🎓 Академическое и языки",
    "subcat": "Английский",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Петрова 16, оф. 24",
    "phone": "+7 707 845 7383",
    "whatsapp": "+7 707 845 7383",
    "instagram": "",
    "rating": 5.0,
    "reviews": 401,
    "schedule": "Пн–Пт 9–22",
    "lat": 51.1487,
    "lon": 71.4672,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 29,
    "name": "OXFORD (Уалиханова)",
    "cat_key": "academic",
    "cat_label": "🎓 Академическое и языки",
    "subcat": "Английский",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Ш. Уалиханова 9/2",
    "phone": "+7 7172 20 18 05",
    "whatsapp": "+7 7172 20 18 05",
    "instagram": "",
    "rating": 4.2,
    "reviews": 5,
    "schedule": "Пн–Пт 9–18",
    "lat": 51.1656,
    "lon": 71.4401,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 30,
    "name": "OXFORD (филиал Сарыарка)",
    "cat_key": "academic",
    "cat_label": "🎓 Академическое и языки",
    "subcat": "Английский",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "р-н Сарыарка",
    "phone": "+7 707 739 1510",
    "whatsapp": "+7 707 739 1510",
    "instagram": "",
    "rating": 5.0,
    "reviews": 5,
    "schedule": "Пн–Пт 9–18",
    "lat": 51.1601,
    "lon": 71.414,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 31,
    "name": "Fast Speak",
    "cat_key": "academic",
    "cat_label": "🎓 Академическое и языки",
    "subcat": "Английский",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Кабанбай батыра 11, ЖК Триумф",
    "phone": "+7 701 880 9660",
    "whatsapp": "+7 701 880 9660",
    "instagram": "",
    "rating": 5.0,
    "reviews": 116,
    "schedule": "Пн–Пт 9–21, Сб 9–17",
    "lat": 51.1403,
    "lon": 71.415,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 32,
    "name": "American School",
    "cat_key": "academic",
    "cat_label": "🎓 Академическое и языки",
    "subcat": "Английский",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Кенесары 52, оф. 10",
    "phone": "+7 701 786 7000",
    "whatsapp": "+7 701 786 7000",
    "instagram": "",
    "rating": 5.0,
    "reviews": 2,
    "schedule": "Пн–Пт 9–20, Сб 10–14",
    "lat": 51.1667,
    "lon": 71.4408,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 33,
    "name": "ELC Astana",
    "cat_key": "academic",
    "cat_label": "🎓 Академическое и языки",
    "subcat": "Английский",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Сыганак 29",
    "phone": "+7 7172 46 62 46",
    "whatsapp": "+7 7172 46 62 46",
    "instagram": "",
    "rating": 4.7,
    "reviews": 62,
    "schedule": "Пн–Пт 9–22, Сб 9–18",
    "lat": 51.1233,
    "lon": 71.4345,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 34,
    "name": "KAZIELTS",
    "cat_key": "academic",
    "cat_label": "🎓 Академическое и языки",
    "subcat": "Английский",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Достык 12",
    "phone": "+7 771 111 6921",
    "whatsapp": "+7 771 111 6921",
    "instagram": "",
    "rating": 5.0,
    "reviews": 40,
    "schedule": "Пн–Сб 12–20:30",
    "lat": 51.1262,
    "lon": 71.4259,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 35,
    "name": "LTC",
    "cat_key": "academic",
    "cat_label": "🎓 Академическое и языки",
    "subcat": "Английский",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Сарайшык 36",
    "phone": "+7 771 011 0003",
    "whatsapp": "+7 771 011 0003",
    "instagram": "",
    "rating": 4.5,
    "reviews": 26,
    "schedule": "Пн–Пт 9–20",
    "lat": 51.1324,
    "lon": 71.4346,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 36,
    "name": "Edustream — языковая академия",
    "cat_key": "academic",
    "cat_label": "🎓 Академическое и языки",
    "subcat": "Английский",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Мәңгілік Ел 23",
    "phone": "+7 707 120 3064",
    "whatsapp": "+7 707 120 3064",
    "instagram": "",
    "rating": 4.8,
    "reviews": 20,
    "schedule": "Пн–Пт 9–20, Сб 10–14",
    "lat": 51.1513,
    "lon": 71.477,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 37,
    "name": "Qazaq Study",
    "cat_key": "academic",
    "cat_label": "🎓 Академическое и языки",
    "subcat": "Казахский язык",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Иманова 19, БЦ Деловой Дом Алма-Ата",
    "phone": "+7 702 472 1271",
    "whatsapp": "+7 702 472 1271",
    "instagram": "",
    "rating": None,
    "reviews": None,
    "schedule": "Пн–Пт 9–20",
    "lat": 51.1648,
    "lon": 71.4422,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 38,
    "name": "Образовательный центр Айплюс (НИШ/РФМШ/БИЛ/ЕНТ)",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Математика",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Туркестан 8/2, БЦ Ансар",
    "phone": "+7 700 754 4475",
    "whatsapp": "+7 700 754 4475",
    "instagram": "",
    "rating": 3.1,
    "reviews": 29,
    "schedule": "Ежедневно 8–20",
    "lat": 51.1186,
    "lon": 71.429,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 39,
    "name": "Образовательный центр Алтын белгі",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "Математика",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "ул. Желтоксан 21 (оф.: Куйши Дина 25/1)",
    "phone": "+7 700 268 5758",
    "whatsapp": "+7 700 268 5758",
    "instagram": "",
    "rating": 4.9,
    "reviews": 161,
    "schedule": "Пн–Сб 11–20",
    "lat": 51.1704,
    "lon": 71.415,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 40,
    "name": "Репетиторская компания Buki",
    "cat_key": "academic",
    "cat_label": "🎓 Академическое и языки",
    "subcat": "Репетиторы",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "Астана",
    "phone": "+7 7172 64 59 45",
    "whatsapp": "+7 7172 64 59 45",
    "instagram": "",
    "rating": 4.9,
    "reviews": 69,
    "schedule": "Пн–Пт 9–18",
    "lat": 51.1569,
    "lon": 71.4322,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 41,
    "name": "Лига Роботов",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "IT / Робототехника",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Туркестан 2 (+3 филиала)",
    "phone": "+7 775 456 7350",
    "whatsapp": "+7 775 456 7350",
    "instagram": "",
    "rating": 4.9,
    "reviews": 42,
    "schedule": "Ежедневно 9–19",
    "lat": 51.12,
    "lon": 71.4297,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 42,
    "name": "Академия Robocode",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "IT / Робототехника",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "Туркестан 8/2, БЦ Olymp Palace, каб. 5",
    "phone": "+7 707 422 4239",
    "whatsapp": "+7 707 422 4239",
    "instagram": "",
    "rating": 5.0,
    "reviews": 5,
    "schedule": "Пн–Чт 10–18, Сб–Вс 11–18",
    "lat": 51.1155,
    "lon": 71.428,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 43,
    "name": "Клуб робототехники «Роботек» (Бейбитшилик)",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "IT / Робототехника",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "ул. Бейбитшилик 33",
    "phone": "+7 7172 46 60 33",
    "whatsapp": "+7 7172 46 60 33",
    "instagram": "",
    "rating": 4.9,
    "reviews": 45,
    "schedule": "Ежедневно 10–22",
    "lat": 51.1752,
    "lon": 71.4177,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 44,
    "name": "Школа робототехники «Роботек» (Туркестан)",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "IT / Робототехника",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "Туркестан 8/3",
    "phone": "+7 7172 98 39 97",
    "whatsapp": "+7 7172 98 39 97",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "—",
    "lat": 51.1142,
    "lon": 71.4299,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 45,
    "name": "Курсы робототехники и программирования",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "IT / Робототехника",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Достык 5",
    "phone": "+7 705 603 0110",
    "whatsapp": "+7 705 603 0110",
    "instagram": "",
    "rating": None,
    "reviews": None,
    "schedule": "Ежедневно 9–20",
    "lat": 51.1287,
    "lon": 71.4229,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 46,
    "name": "Академия ШАГ / IT Step Academy",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "IT / Робототехника",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Сыганак 47, БЦ Евроцентр",
    "phone": "+7 771 936 5066",
    "whatsapp": "+7 771 936 5066",
    "instagram": "",
    "rating": 4.9,
    "reviews": 495,
    "schedule": "Ежедневно 10–19",
    "lat": 51.123,
    "lon": 71.4343,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 47,
    "name": "Центр программирования Runtime",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "IT / Робототехника",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Амангельды Иманова 19",
    "phone": "+7 702 411 1198",
    "whatsapp": "+7 702 411 1198",
    "instagram": "",
    "rating": 4.0,
    "reviews": 4,
    "schedule": "Ежедневно 9–21",
    "lat": 51.1647,
    "lon": 71.4414,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 48,
    "name": "Курсы программирования Mol Ayti",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "IT / Робототехника",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Достык 3",
    "phone": "+7 700 912 0952",
    "whatsapp": "+7 700 912 0952",
    "instagram": "",
    "rating": 5.0,
    "reviews": 4,
    "schedule": "Ежедневно 8–22",
    "lat": 51.1281,
    "lon": 71.4201,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 49,
    "name": "Школа программирования Softium",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "IT / Робототехника",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Г. Мусрепова 7/2",
    "phone": "+7 747 777 3457",
    "whatsapp": "+7 747 777 3457",
    "instagram": "",
    "rating": None,
    "reviews": None,
    "schedule": "Ежедневно 10–20",
    "lat": 51.1539,
    "lon": 71.499,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 50,
    "name": "IT школа Code:ME",
    "cat_key": "mind",
    "cat_label": "🧠 Ум и логика",
    "subcat": "IT / Робототехника",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Сыганак 54а, оф. 408",
    "phone": "+7 777 533 6755",
    "whatsapp": "+7 777 533 6755",
    "instagram": "",
    "rating": None,
    "reviews": None,
    "schedule": "Пн–Пт 9–18, Сб–Вс 10–18",
    "lat": 51.1242,
    "lon": 71.4181,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 51,
    "name": "Dream Way Dance And Art Lab",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Танцы",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Кошкарбаева 2, НП 22-26",
    "phone": "+7 701 984 4498",
    "whatsapp": "+7 701 984 4498",
    "instagram": "",
    "rating": 5.0,
    "reviews": 67,
    "schedule": "Пн–Пт 10–22, Сб 12–21, Вс 12–18",
    "lat": 51.1284,
    "lon": 71.4621,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 52,
    "name": "Студия танцев Tribal Pro",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Танцы",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "просп. Абая 8",
    "phone": "+7 775 327 9934",
    "whatsapp": "+7 775 327 9934",
    "instagram": "",
    "rating": 4.7,
    "reviews": 142,
    "schedule": "Ежедневно 9–22",
    "lat": 51.1656,
    "lon": 71.4055,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 53,
    "name": "Школа балета Prima (Экспо)",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Танцы",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Туркестан 34Б",
    "phone": "+7 702 000 1648",
    "whatsapp": "+7 702 000 1648",
    "instagram": "",
    "rating": 4.5,
    "reviews": 17,
    "schedule": "Ежедневно 12–21",
    "lat": 51.0941,
    "lon": 71.4203,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 54,
    "name": "Студия танцев «Тулпар»",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Танцы",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. А. Иманова 3",
    "phone": "+7 701 608 9831",
    "whatsapp": "+7 701 608 9831",
    "instagram": "",
    "rating": 4.3,
    "reviews": 23,
    "schedule": "Ежедневно 9–22",
    "lat": 51.1633,
    "lon": 71.4298,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 55,
    "name": "Танцы для детей Happy Motion",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Танцы",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "ул. С. Сейфуллина",
    "phone": "+7 775 672 4411",
    "whatsapp": "+7 775 672 4411",
    "instagram": "",
    "rating": 5.0,
    "reviews": 10,
    "schedule": "Ежедневно 8–21",
    "lat": 51.1717,
    "lon": 71.4249,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 56,
    "name": "United Dance Space",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Танцы",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "просп. Богенбай батыра 56а",
    "phone": "+7 700 795 0803",
    "whatsapp": "+7 700 795 0803",
    "instagram": "",
    "rating": 5.0,
    "reviews": 4,
    "schedule": "Пн–Пт 11–22",
    "lat": 51.1767,
    "lon": 71.4259,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 57,
    "name": "Студия танца «Гульнар» (Женис)",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Танцы",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "просп. Женис 47",
    "phone": "+7 702 729 7766",
    "whatsapp": "+7 702 729 7766",
    "instagram": "",
    "rating": 4.4,
    "reviews": 7,
    "schedule": "—",
    "lat": 51.1797,
    "lon": 71.4094,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 58,
    "name": "Ансамбль народного танца «Гульнар» (Сарыарка)",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Танцы",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "просп. Сарыарка 21",
    "phone": "+7 702 729 7766",
    "whatsapp": "+7 702 729 7766",
    "instagram": "",
    "rating": 5.0,
    "reviews": 5,
    "schedule": "По расписанию",
    "lat": 51.1698,
    "lon": 71.4073,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 59,
    "name": "Cool Space",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "HighVill, ул. Буырат 4А, блок E",
    "phone": "+7 7172 22 92 22",
    "whatsapp": "+7 7172 22 92 22",
    "instagram": "",
    "rating": 4.5,
    "reviews": 2,
    "schedule": "Ежедневно",
    "lat": 51.1268,
    "lon": 71.4683,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 60,
    "name": "Художественно-образовательный центр «Арнау»",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Рисование / ИЗО",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Кенесары 44",
    "phone": "+7 7172 21 35 83",
    "whatsapp": "+7 7172 21 35 83",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "Ср–Вс 9–20",
    "lat": 51.1661,
    "lon": 71.4358,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 61,
    "name": "AvangART — школа академического рисунка",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Рисование / ИЗО",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "ул. Кенесары 25, каб. 310-311",
    "phone": "+7 707 809 0203",
    "whatsapp": "+7 707 809 0203",
    "instagram": "",
    "rating": 5.0,
    "reviews": 4,
    "schedule": "Пн–Чт 10–20:45, Сб–Вс 10–19",
    "lat": 51.1641,
    "lon": 71.4138,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 62,
    "name": "Dream School (Сарыарка) — рисование и гитара",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Музыка / Вокал",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "ул. С. Сейфуллина 4/1, ВП-15",
    "phone": "+7 706 674 8510",
    "whatsapp": "+7 706 674 8510",
    "instagram": "",
    "rating": 5.0,
    "reviews": 3,
    "schedule": "Ежедневно 10–20",
    "lat": 51.1674,
    "lon": 71.4012,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 63,
    "name": "Dream School (Нура) — рисование и гитара",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Музыка / Вокал",
    "dist_key": "nura",
    "dist_label": "Нура/Есиль-запад",
    "address": "Анет баба 9/2, НП 2",
    "phone": "+7 777 174 8510",
    "whatsapp": "+7 777 174 8510",
    "instagram": "",
    "rating": 5.0,
    "reviews": 2,
    "schedule": "Ежедневно 10–20",
    "lat": 51.1369,
    "lon": 71.3835,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 64,
    "name": "Художественная школа (Гейдара Алиева)",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Рисование / ИЗО",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Гейдара Алиева 6",
    "phone": "",
    "whatsapp": "",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "—",
    "lat": 51.1187,
    "lon": 71.4186,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 65,
    "name": "Pon Школа Indigo",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Рисование / ИЗО",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "просп. Абылай хана 9/4",
    "phone": "+7 702 517 7843",
    "whatsapp": "+7 702 517 7843",
    "instagram": "",
    "rating": 4.7,
    "reviews": 26,
    "schedule": "Пн–Вс 9–18",
    "lat": 51.1606,
    "lon": 71.4758,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 66,
    "name": "Творческая студия Happy Art",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Творчество",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. К. Сатпаева 1/1",
    "phone": "+7 708 261 6961",
    "whatsapp": "+7 708 261 6961",
    "instagram": "",
    "rating": 5.0,
    "reviews": 2,
    "schedule": "Пн–Сб 9–20",
    "lat": 51.1523,
    "lon": 71.466,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 67,
    "name": "Astana ART",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Рисование / ИЗО",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "просп. Сарыарка 17, оф. 19",
    "phone": "+7 701 866 8313",
    "whatsapp": "+7 701 866 8313",
    "instagram": "",
    "rating": 4.3,
    "reviews": 3,
    "schedule": "Ежедневно 10–21",
    "lat": 51.1688,
    "lon": 71.4077,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 68,
    "name": "Artlab школа",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Рисование / ИЗО",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "просп. Богенбай батыра 56",
    "phone": "+7 776 975 9510",
    "whatsapp": "+7 776 975 9510",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "Ежедневно 9–22",
    "lat": 51.1772,
    "lon": 71.4285,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 69,
    "name": "Студия гончарного искусства Art Maiolica",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Рисование / ИЗО",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Улы Дала 23, ЖК Арнау-3",
    "phone": "+7 708 202 2777",
    "whatsapp": "+7 708 202 2777",
    "instagram": "",
    "rating": 4.0,
    "reviews": 4,
    "schedule": "Ежедневно 10–20",
    "lat": 51.0949,
    "lon": 71.4353,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 70,
    "name": "Adeena Ceramics",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Рисование / ИЗО",
    "dist_key": "nura",
    "dist_label": "Нура/Есиль-запад",
    "address": "Роза Багланова 6/2",
    "phone": "+7 747 476 3370",
    "whatsapp": "+7 747 476 3370",
    "instagram": "",
    "rating": None,
    "reviews": None,
    "schedule": "Ежедневно 11–21",
    "lat": 51.1157,
    "lon": 71.393,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 71,
    "name": "Центр искусства и знаний Молдир Мукановой",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Творчество",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Темирказык 63",
    "phone": "",
    "whatsapp": "",
    "instagram": "",
    "rating": 5.0,
    "reviews": 2,
    "schedule": "—",
    "lat": 51.1418,
    "lon": 71.4284,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 72,
    "name": "Музыкальная школа «Скрипичный ключ»",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Музыка / Вокал",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Мәңгілік Ел 17, НП 149",
    "phone": "+7 778 927 5495",
    "whatsapp": "+7 778 927 5495",
    "instagram": "",
    "rating": None,
    "reviews": None,
    "schedule": "Ежедневно 9–21",
    "lat": 51.1162,
    "lon": 71.4336,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 73,
    "name": "Live Band",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Музыка / Вокал",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Мәңгілік Ел 19",
    "phone": "+7 747 730 2912",
    "whatsapp": "+7 747 730 2912",
    "instagram": "",
    "rating": 4.8,
    "reviews": 6,
    "schedule": "Ежедневно 9–21",
    "lat": 51.1142,
    "lon": 71.4327,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 74,
    "name": "Центр искусств AMANAT",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Музыка / Вокал",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Кабанбай батыра 11, ВП-44",
    "phone": "+7 701 125 9020",
    "whatsapp": "+7 701 125 9020",
    "instagram": "",
    "rating": 5.0,
    "reviews": 4,
    "schedule": "Пн–Сб 9–20",
    "lat": 51.1393,
    "lon": 71.4159,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 75,
    "name": "AsylArt — музыкальная школа",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Музыка / Вокал",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. К. Сатпаева 20/1",
    "phone": "+7 702 334 5581",
    "whatsapp": "+7 702 334 5581",
    "instagram": "",
    "rating": 4.9,
    "reviews": 12,
    "schedule": "Ежедневно 9–21",
    "lat": 51.1428,
    "lon": 71.4729,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 76,
    "name": "Sartay Music",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Музыка / Вокал",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Д. Конаева 35",
    "phone": "+7 775 091 0322",
    "whatsapp": "+7 775 091 0322",
    "instagram": "",
    "rating": 4.2,
    "reviews": 5,
    "schedule": "Ежедневно 9–21",
    "lat": 51.1306,
    "lon": 71.4356,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 77,
    "name": "Starlight — вокал, гитара, фортепиано",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Музыка / Вокал",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Мәңгілік Ел 19",
    "phone": "",
    "whatsapp": "",
    "instagram": "",
    "rating": 5.0,
    "reviews": 32,
    "schedule": "Ежедневно 9–21",
    "lat": 51.1143,
    "lon": 71.4328,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 78,
    "name": "Обучение вокалу + студия звукозаписи",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Музыка / Вокал",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Б. Майлина 8/1, БЦ Жарык, 2 эт.",
    "phone": "+7 775 253 2914",
    "whatsapp": "+7 775 253 2914",
    "instagram": "",
    "rating": 5.0,
    "reviews": 5,
    "schedule": "Ежедневно 9–17",
    "lat": 51.143,
    "lon": 71.4691,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 79,
    "name": "Music Vibe",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Музыка / Вокал",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Буырат 15",
    "phone": "+7 776 650 6868",
    "whatsapp": "+7 776 650 6868",
    "instagram": "",
    "rating": 5.0,
    "reviews": 3,
    "schedule": "Ежедневно 10–21",
    "lat": 51.1261,
    "lon": 71.4845,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 80,
    "name": "Детская музыкальная школа №2 (гос.)",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Музыка / Вокал",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Ш. Айманова",
    "phone": "+7 7172 43 70 49",
    "whatsapp": "+7 7172 43 70 49",
    "instagram": "",
    "rating": 5.0,
    "reviews": 10,
    "schedule": "Пн–Пт 9–18",
    "lat": 51.1743,
    "lon": 71.4307,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 81,
    "name": "Городская музыкальная школа №3 (гос.)",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Музыка / Вокал",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Б. Бейсекбаева 2",
    "phone": "",
    "whatsapp": "",
    "instagram": "",
    "rating": 4.8,
    "reviews": 10,
    "schedule": "—",
    "lat": 51.1623,
    "lon": 71.453,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 82,
    "name": "KERN Hub",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Творчество",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "р-н Есиль (4CC3+XGF)",
    "phone": "+7 708 010 7788",
    "whatsapp": "+7 708 010 7788",
    "instagram": "",
    "rating": 4.5,
    "reviews": 23,
    "schedule": "Пн–Пт 8–20, Сб–Вс 10–18",
    "lat": 51.1227,
    "lon": 71.4045,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 83,
    "name": "Федерация художественной гимнастики г. Астана",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Достык 3",
    "phone": "+7 7172 57 66 76",
    "whatsapp": "+7 7172 57 66 76",
    "instagram": "",
    "rating": 4.4,
    "reviews": 52,
    "schedule": "Ежедневно 9–22",
    "lat": 51.1281,
    "lon": 71.4193,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 84,
    "name": "Академия гимнастики «Лидер»",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Кабанбай батыра 29А",
    "phone": "+7 776 688 7711",
    "whatsapp": "+7 776 688 7711",
    "instagram": "",
    "rating": 5.0,
    "reviews": 10,
    "schedule": "Пн–Пт 17–20, Сб–Вс 18–20",
    "lat": 51.1236,
    "lon": 71.4119,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 85,
    "name": "Fit Baby",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "nura",
    "dist_label": "Нура/Есиль-запад",
    "address": "просп. Кабанбай батыра 53",
    "phone": "+7 778 979 3000",
    "whatsapp": "+7 778 979 3000",
    "instagram": "",
    "rating": 4.2,
    "reviews": 5,
    "schedule": "Ежедневно 10–20",
    "lat": 51.093,
    "lon": 71.3965,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 86,
    "name": "Школа художественной гимнастики «Жулдыз»",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "Дворец спорта Алатау",
    "phone": "+7 701 506 5015",
    "whatsapp": "+7 701 506 5015",
    "instagram": "",
    "rating": 4.0,
    "reviews": 8,
    "schedule": "—",
    "lat": 51.1079,
    "lon": 71.403,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 87,
    "name": "Astana Triathlon Federation (бассейн)",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "nura",
    "dist_label": "Нура/Есиль-запад",
    "address": "р-н Барыс Арены (495V+WP8)",
    "phone": "+7 7172 61 34 40",
    "whatsapp": "+7 7172 61 34 40",
    "instagram": "",
    "rating": 4.8,
    "reviews": 82,
    "schedule": "Ежедневно 8–22",
    "lat": 51.1098,
    "lon": 71.3943,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 88,
    "name": "SwimTime",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "nura",
    "dist_label": "Нура/Есиль-запад",
    "address": "р-н Барыс Арены",
    "phone": "+7 702 426 0102",
    "whatsapp": "+7 702 426 0102",
    "instagram": "",
    "rating": 4.7,
    "reviews": 7,
    "schedule": "Ежедневно",
    "lat": 51.1094,
    "lon": 71.3939,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 89,
    "name": "Qazswimacademy",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "nura",
    "dist_label": "Нура/Есиль-запад",
    "address": "ул. Сыганак 34",
    "phone": "",
    "whatsapp": "",
    "instagram": "",
    "rating": 4.9,
    "reviews": 10,
    "schedule": "—",
    "lat": 51.1266,
    "lon": 71.3961,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 90,
    "name": "Бассейн «Барыс Арена»",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "nura",
    "dist_label": "Нура/Есиль-запад",
    "address": "просп. Туран 57",
    "phone": "+7 7172 61 34 40",
    "whatsapp": "+7 7172 61 34 40",
    "instagram": "",
    "rating": 4.7,
    "reviews": 149,
    "schedule": "Ежедневно 7–22",
    "lat": 51.1093,
    "lon": 71.3954,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 91,
    "name": "Fit Arena Winox (бассейн)",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "ул. Ш. Косшыгулулы 24",
    "phone": "+7 701 345 6802",
    "whatsapp": "+7 701 345 6802",
    "instagram": "",
    "rating": 4.7,
    "reviews": 224,
    "schedule": "Ежедневно 7–23",
    "lat": 51.1729,
    "lon": 71.3796,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 92,
    "name": "Дворец Жастар (бассейн, секции)",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "просп. Республики 34",
    "phone": "+7 702 431 2777",
    "whatsapp": "+7 702 431 2777",
    "instagram": "",
    "rating": 4.3,
    "reviews": 676,
    "schedule": "Ежедневно 10–22",
    "lat": 51.1701,
    "lon": 71.4278,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 93,
    "name": "Центр дзюдо Астана",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Тауелсиздик 1",
    "phone": "+7 701 521 7355",
    "whatsapp": "+7 701 521 7355",
    "instagram": "",
    "rating": 4.7,
    "reviews": 78,
    "schedule": "Ежедневно 9–23",
    "lat": 51.1515,
    "lon": 71.4506,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 94,
    "name": "Академия единоборств Kazakh Batyr",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Мәңгілік Ел 17а",
    "phone": "+7 702 000 1140",
    "whatsapp": "+7 702 000 1140",
    "instagram": "",
    "rating": 4.6,
    "reviews": 56,
    "schedule": "Ежедневно 10–22",
    "lat": 51.1162,
    "lon": 71.4324,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 95,
    "name": "Qazaq Batyry (Сыганак)",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Сыганак 17",
    "phone": "+7 702 000 1140",
    "whatsapp": "+7 702 000 1140",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "—",
    "lat": 51.1245,
    "lon": 71.4238,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 96,
    "name": "Клуб единоборств Qaharman",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Б. Майлина 7/1",
    "phone": "+7 702 877 7444",
    "whatsapp": "+7 702 877 7444",
    "instagram": "",
    "rating": 5.0,
    "reviews": 4,
    "schedule": "Ежедневно 9–22",
    "lat": 51.1435,
    "lon": 71.4683,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 97,
    "name": "Oidene-Fight — школа боевых искусств",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Тараз 2",
    "phone": "+7 708 880 0098",
    "whatsapp": "+7 708 880 0098",
    "instagram": "",
    "rating": 4.7,
    "reviews": 26,
    "schedule": "Пн–Пт 9–22, Сб 9–19",
    "lat": 51.1632,
    "lon": 71.4443,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 98,
    "name": "Центр традиционного таэквондо (братья Абеновы)",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Калдаякова 15, ЖК Сулу",
    "phone": "+7 778 541 6924",
    "whatsapp": "+7 778 541 6924",
    "instagram": "",
    "rating": 4.3,
    "reviews": 17,
    "schedule": "Пн/Ср/Пт 9–21",
    "lat": 51.1165,
    "lon": 71.4756,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 99,
    "name": "Kodokan Spirit",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "nura",
    "dist_label": "Нура/Есиль-запад",
    "address": "р-н Нура (49C5+5F9)",
    "phone": "",
    "whatsapp": "",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "—",
    "lat": 51.1204,
    "lon": 71.3587,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 100,
    "name": "Дзюдо клуб «Ортус»",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "р-н Алматинский (4FXR+WVG)",
    "phone": "",
    "whatsapp": "",
    "instagram": "",
    "rating": 5.0,
    "reviews": 2,
    "schedule": "—",
    "lat": 51.1498,
    "lon": 71.4922,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 101,
    "name": "Bronx Boxing Club",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Достык 18",
    "phone": "+7 707 130 8888",
    "whatsapp": "+7 707 130 8888",
    "instagram": "",
    "rating": 5.0,
    "reviews": 13,
    "schedule": "Пн–Пт 7–22, Сб 10–20, Вс 10–18",
    "lat": 51.1246,
    "lon": 71.434,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 102,
    "name": "Боксёрский клуб Астана",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Кордай 21",
    "phone": "+7 701 762 0005",
    "whatsapp": "+7 701 762 0005",
    "instagram": "",
    "rating": 4.4,
    "reviews": 76,
    "schedule": "Ежедневно",
    "lat": 51.1392,
    "lon": 71.5002,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 103,
    "name": "Rocky Boxing Club",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "ул. Кенесары 4",
    "phone": "+7 777 183 3636",
    "whatsapp": "+7 777 183 3636",
    "instagram": "",
    "rating": 5.0,
    "reviews": 16,
    "schedule": "Ежедневно 7–22",
    "lat": 51.1616,
    "lon": 71.4019,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 104,
    "name": "Old School Boxing Club",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Туран 19",
    "phone": "+7 701 042 0031",
    "whatsapp": "+7 701 042 0031",
    "instagram": "",
    "rating": 4.4,
    "reviews": 7,
    "schedule": "Ежедневно 7–23",
    "lat": 51.1444,
    "lon": 71.4105,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 105,
    "name": "Клуб Бокс (Тауелсиздик)",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Тауелсиздик 34/1",
    "phone": "+7 702 000 1040",
    "whatsapp": "+7 702 000 1040",
    "instagram": "",
    "rating": 4.3,
    "reviews": 3,
    "schedule": "Ежедневно 9–22",
    "lat": 51.1393,
    "lon": 71.4736,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 106,
    "name": "Футбольная школа Akmola",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Керей-Жанибек хандар 18",
    "phone": "+7 708 323 2040",
    "whatsapp": "+7 708 323 2040",
    "instagram": "",
    "rating": 5.0,
    "reviews": 2,
    "schedule": "Ежедневно 10–22",
    "lat": 51.1137,
    "lon": 71.425,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 107,
    "name": "Футбольная академия Санлин (Дворец Жастар)",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "просп. Республики 34",
    "phone": "+7 702 431 2777",
    "whatsapp": "+7 702 431 2777",
    "instagram": "",
    "rating": 4.3,
    "reviews": 676,
    "schedule": "Ежедневно 10–22",
    "lat": 51.1701,
    "lon": 71.4278,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 108,
    "name": "Футбольная школа ZhaStar (филиал №1)",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Кабанбай батыра 47",
    "phone": "+7 701 199 4499",
    "whatsapp": "+7 701 199 4499",
    "instagram": "",
    "rating": 5.0,
    "reviews": 16,
    "schedule": "—",
    "lat": 51.1044,
    "lon": 71.4079,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 109,
    "name": "Футбольная школа Юниор Астана",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Тауелсиздик 1Б",
    "phone": "+7 778 900 6566",
    "whatsapp": "+7 778 900 6566",
    "instagram": "",
    "rating": 4.3,
    "reviews": 4,
    "schedule": "Ежедневно",
    "lat": 51.1506,
    "lon": 71.4562,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 110,
    "name": "Footbik Astana — голландский футбольный центр",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Буырат 8",
    "phone": "+7 747 729 7521",
    "whatsapp": "+7 747 729 7521",
    "instagram": "",
    "rating": 5.0,
    "reviews": 4,
    "schedule": "Ежедневно 9–21",
    "lat": 51.1275,
    "lon": 71.4673,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 111,
    "name": "Steppe Dunk — школа баскетбола",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "РФМШ Haileybury, Туркестан 2/1",
    "phone": "+7 707 563 9527",
    "whatsapp": "+7 707 563 9527",
    "instagram": "",
    "rating": 4.5,
    "reviews": 25,
    "schedule": "Ежедневно 9–21",
    "lat": 51.1194,
    "lon": 71.4317,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 112,
    "name": "Треnироffка (Иманбаевой)",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Иманбаевой 2",
    "phone": "+7 705 303 8470",
    "whatsapp": "+7 705 303 8470",
    "instagram": "",
    "rating": 5.0,
    "reviews": 3,
    "schedule": "Пн–Пт 7–23",
    "lat": 51.1598,
    "lon": 71.4365,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 113,
    "name": "Национальный теннисный центр",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Туран 6/1а",
    "phone": "+7 7172 24 32 22",
    "whatsapp": "+7 7172 24 32 22",
    "instagram": "",
    "rating": 4.7,
    "reviews": 172,
    "schedule": "Ежедневно 8–24",
    "lat": 51.1512,
    "lon": 71.4194,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 114,
    "name": "СК «Даулет» (теннис)",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Туран 4/2",
    "phone": "+7 7172 24 32 22",
    "whatsapp": "+7 7172 24 32 22",
    "instagram": "",
    "rating": 4.6,
    "reviews": 545,
    "schedule": "Ежедневно 7–24",
    "lat": 51.1529,
    "lon": 71.4199,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 115,
    "name": "Daulet Tennis Centre (Кордай)",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Кордай 6",
    "phone": "+7 706 641 0485",
    "whatsapp": "+7 706 641 0485",
    "instagram": "",
    "rating": 4.7,
    "reviews": 102,
    "schedule": "Ежедневно 7–23",
    "lat": 51.1416,
    "lon": 71.4993,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 116,
    "name": "Теннис Астана / RoyalAce Tennis",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "nura",
    "dist_label": "Нура/Есиль-запад",
    "address": "ул. Е 103, 7/2",
    "phone": "+7 707 952 6119",
    "whatsapp": "+7 707 952 6119",
    "instagram": "",
    "rating": 4.8,
    "reviews": 68,
    "schedule": "Ежедневно 7–23",
    "lat": 51.083,
    "lon": 71.3778,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 117,
    "name": "Клуб настольного тенниса (Ракымова)",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Ген. С. Ракымова 22",
    "phone": "+7 701 389 2873",
    "whatsapp": "+7 701 389 2873",
    "instagram": "",
    "rating": 5.0,
    "reviews": 6,
    "schedule": "Ежедневно 11–02",
    "lat": 51.1622,
    "lon": 71.4392,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 118,
    "name": "ADD Padel Indoor",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "Тауелсиздик 1б",
    "phone": "+7 705 777 5793",
    "whatsapp": "+7 705 777 5793",
    "instagram": "",
    "rating": 5.0,
    "reviews": 6,
    "schedule": "Ежедневно 10–24",
    "lat": 51.1514,
    "lon": 71.454,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 119,
    "name": "Скалодром Climbers Garden",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. А. Бокейхана 34",
    "phone": "+7 707 307 4242",
    "whatsapp": "+7 707 307 4242",
    "instagram": "",
    "rating": 4.8,
    "reviews": 15,
    "schedule": "Пн–Пт 17–22, Сб–Вс 9–22",
    "lat": 51.0933,
    "lon": 71.4293,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 120,
    "name": "Спортклуб Apriori (бассейн)",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "Коргалжынское шоссе 2а",
    "phone": "+7 701 225 7677",
    "whatsapp": "+7 701 225 7677",
    "instagram": "",
    "rating": 4.5,
    "reviews": 321,
    "schedule": "Ежедневно 7–23",
    "lat": 51.1489,
    "lon": 71.4161,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 121,
    "name": "Alau (ледовый дворец)",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Кабанбай батыра 47",
    "phone": "+7 7172 57 16 12",
    "whatsapp": "+7 7172 57 16 12",
    "instagram": "",
    "rating": 4.7,
    "reviews": 141,
    "schedule": "Пн–Пт 9–18",
    "lat": 51.1043,
    "lon": 71.4049,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 122,
    "name": "ICE STARS (фигурное катание)",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "Кабанбай батыра",
    "phone": "+7 702 882 6361",
    "whatsapp": "+7 702 882 6361",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "Пн–Пт вечер",
    "lat": 51.115,
    "lon": 71.4127,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 123,
    "name": "СК Alatau (секции)",
    "cat_key": "sport",
    "cat_label": "🤸 Спорт",
    "subcat": "Спорт",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Тауелсиздик 1/1",
    "phone": "+7 7172 71 47 23",
    "whatsapp": "+7 7172 71 47 23",
    "instagram": "",
    "rating": 4.4,
    "reviews": 2301,
    "schedule": "Ежедневно 8–22",
    "lat": 51.1517,
    "lon": 71.4513,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 124,
    "name": "СК Tolqyn",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Тауелсиздик 2",
    "phone": "+7 775 347 4745",
    "whatsapp": "+7 775 347 4745",
    "instagram": "",
    "rating": 4.5,
    "reviews": 185,
    "schedule": "Ежедневно 9–20",
    "lat": 51.154,
    "lon": 71.4557,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 125,
    "name": "Academy MMA Kazakhstan",
    "cat_key": "combat",
    "cat_label": "🥋 Единоборства",
    "subcat": "Единоборства",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "просп. Абая 19",
    "phone": "+7 747 111 6877",
    "whatsapp": "+7 747 111 6877",
    "instagram": "",
    "rating": 5.0,
    "reviews": 17,
    "schedule": "Пн–Сб 9–22",
    "lat": 51.1668,
    "lon": 71.4113,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 126,
    "name": "Детский центр коррекции речи и поведения Дроновой И.Н.",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "almaty",
    "dist_label": "Алматинский",
    "address": "ул. Отырар 4/2",
    "phone": "+7 702 028 4929",
    "whatsapp": "+7 702 028 4929",
    "instagram": "",
    "rating": None,
    "reviews": None,
    "schedule": "Пн–Пт 8–18",
    "lat": 51.1678,
    "lon": 71.4318,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 127,
    "name": "Детский коррекционный центр BALA",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Туран 14",
    "phone": "+7 705 892 9809",
    "whatsapp": "+7 705 892 9809",
    "instagram": "",
    "rating": 5.0,
    "reviews": 5,
    "schedule": "Пн–Пт 9–20, Сб 10–17",
    "lat": 51.1427,
    "lon": 71.4132,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 128,
    "name": "Детская академия речи",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Петрова 26",
    "phone": "+7 701 486 5005",
    "whatsapp": "+7 701 486 5005",
    "instagram": "",
    "rating": None,
    "reviews": None,
    "schedule": "Ежедневно 10–18",
    "lat": 51.151,
    "lon": 71.4777,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 129,
    "name": "Master Slova — школа ораторского искусства",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Театр / Ораторское",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Акмешит 19/1, AmideliHUB",
    "phone": "+7 701 886 2890",
    "whatsapp": "+7 701 886 2890",
    "instagram": "",
    "rating": 5.0,
    "reviews": 141,
    "schedule": "Ежедневно 10–22",
    "lat": 51.0965,
    "lon": 71.4151,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 130,
    "name": "GM Talent — модельная школа для детей",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Модельная школа",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "ул. Сарайшык 27/3",
    "phone": "+7 701 085 4343",
    "whatsapp": "+7 701 085 4343",
    "instagram": "",
    "rating": 5.0,
    "reviews": 5,
    "schedule": "Ежедневно 10–20",
    "lat": 51.1345,
    "lon": 71.4273,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 131,
    "name": "Professional — школа театра и кино",
    "cat_key": "art",
    "cat_label": "🎨 Творчество",
    "subcat": "Театр / Ораторское",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "р-н Есиль (4CH5+32G)",
    "phone": "",
    "whatsapp": "",
    "instagram": "",
    "rating": 5.0,
    "reviews": 1,
    "schedule": "—",
    "lat": 51.1277,
    "lon": 71.4076,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 132,
    "name": "Дворец школьников (Мамбетова)",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "ул. А. Мамбетова 1",
    "phone": "+7 7172 32 49 89",
    "whatsapp": "+7 7172 32 49 89",
    "instagram": "",
    "rating": 4.5,
    "reviews": 1388,
    "schedule": "Ежедневно 9–21",
    "lat": 51.1618,
    "lon": 71.4228,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 133,
    "name": "Дворец школьников (Момышулы)",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "esil",
    "dist_label": "Есиль",
    "address": "просп. Б. Момышулы 5",
    "phone": "+7 7172 70 12 71",
    "whatsapp": "+7 7172 70 12 71",
    "instagram": "",
    "rating": 4.6,
    "reviews": 3926,
    "schedule": "Пн–Сб",
    "lat": 51.137,
    "lon": 71.4639,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  },
  {
    "id": 134,
    "name": "Childrens' Club (Абая 8)",
    "cat_key": "development",
    "cat_label": "🌱 Развитие ребёнка",
    "subcat": "Развитие / Подготовка",
    "dist_key": "saryarka",
    "dist_label": "Сарыарка/Байконур",
    "address": "просп. Абая 8",
    "phone": "+7 777 034 1003",
    "whatsapp": "+7 777 034 1003",
    "instagram": "",
    "rating": 4.5,
    "reviews": 4,
    "schedule": "Ежедневно 9–21",
    "lat": 51.1652,
    "lon": 71.4047,
    "price_min": None,
    "price_max": None,
    "age_from": None,
    "age_to": None,
    "group_size": "",
    "trial": "",
    "discount": "",
    "status": "В базе (импорт)",
    "confirmed_date": ""
  }
]


# ─── ЗАГРУЗКА ЦЕНТРОВ (Google Sheets с кэшем; иначе встроенный список) ───
import time as _time
try:
    import sheets as _sheets
except Exception:
    _sheets = None

_CACHE = {"data": None, "ts": 0}
_TTL = 300  # сек: правки Чингиза в таблице подтягиваются раз в 5 минут

# соответствие: заголовок в листе "Центры" → ключ, которым пользуется бот
_COLMAP = {
    "id": "id", "Название": "name", "Категория": "cat_label",
    "Ключ_категории": "cat_key", "Подкатегория": "subcat",
    "Район": "dist_label", "Ключ_района": "dist_key", "Адрес": "address",
    "Телефон": "phone", "WhatsApp": "whatsapp", "Instagram": "instagram",
    "Рейтинг": "rating", "Отзывов": "reviews", "График": "schedule",
    "Широта": "lat", "Долгота": "lon",
    "Цена_мин": "price_min", "Цена_макс": "price_max",
    "Возраст_от": "age_from", "Возраст_до": "age_to",
    "Размер_группы": "group_size", "Пробное_занятие": "trial",
    "Скидка_OZI": "discount", "Статус": "status",
    "Дата_подтверждения": "confirmed_date",
}

def _num(v):
    if v in ("", None): return None
    try:
        f = float(str(v).replace(",", "."))
        return int(f) if f == int(f) else f
    except Exception:
        return None

def _row_to_center(r):
    c = {}
    for col, key in _COLMAP.items():
        c[key] = r.get(col, "")
    for k in ("id", "reviews", "price_min", "price_max", "age_from", "age_to"):
        c[k] = _num(c.get(k))
    c["rating"] = _num(c.get("rating"))
    c["lat"] = _num(c.get("lat")); c["lon"] = _num(c.get("lon"))
    if not c.get("status"): c["status"] = "В базе (импорт)"
    return c

def load_centers():
    """Из Google Sheets (кэш 5 мин). Если Sheets недоступны — встроенный список из 134."""
    if _sheets and _sheets.available():
        now = _time.time()
        if _CACHE["data"] is not None and now - _CACHE["ts"] < _TTL:
            return _CACHE["data"]
        recs = _sheets.read_records("Центры")
        if recs:
            data = [_row_to_center(r) for r in recs if r.get("Название")]
            if data:
                _CACHE["data"] = data
                _CACHE["ts"] = now
                return data
    return CENTERS  # fallback: встроенные 134


def _rating_key(c):
    # верифицированные ("Данные подтверждены") — выше; далее по рейтингу
    conf = 1 if c.get("status", "").startswith("Данные подтверждены") else 0
    return (conf, c.get("rating") or 0)


def search_centers(cat_key=None, age=None, dist_key=None, budget_key=None, limit=None):
    res = load_centers()
    if cat_key and cat_key != "any":
        res = [c for c in res if c["cat_key"] == cat_key]
    if dist_key and dist_key != "any":
        res = [c for c in res if c["dist_key"] == dist_key]
    if age is not None:
        # фильтруем только если у центра указан возраст (поле Чингиза); иначе не отсекаем
        res = [c for c in res if not (c.get("age_from") and c.get("age_to"))
               or (c["age_from"] <= age <= c["age_to"])]
    if budget_key and budget_key != "any":
        bmin, bmax, _ = BUDGETS[budget_key]
        # фильтруем только если цена известна; неизвестную цену не отсекаем
        def price_ok(c):
            if not c.get("price_min") and not c.get("price_max"):
                return True
            pm = c.get("price_min") or 0
            px = c.get("price_max") or pm
            return pm <= bmax and px >= bmin
        res = [c for c in res if price_ok(c)]
    res = sorted(res, key=_rating_key, reverse=True)
    return res[:limit] if limit else res


def text_search(query, limit=8):
    """Поиск по буквам: название, подкатегория, категория."""
    q = query.lower().strip()
    if len(q) < 2:
        return []
    out = []
    for c in load_centers():
        hay = f"{c['name']} {c['subcat']} {c['cat_label']}".lower()
        if q in hay:
            out.append(c)
    return sorted(out, key=_rating_key, reverse=True)[:limit]


def get_center(cid):
    for c in load_centers():
        if c["id"] == cid:
            return c
    return None


def format_card(c, idx=None, total=None):
    # статус доверия
    if c.get("status", "").startswith("Данные подтверждены"):
        d = c.get("confirmed_date", "")
        status = f"✅ Данные подтверждены OZI{(' · ' + d) if d else ''}"
    else:
        status = "⏳ Кандидат: данные на верификации"

    # рейтинг
    if c.get("rating"):
        stars = "⭐" * int(round(c["rating"]))
        rv = f" ({c['reviews']} отз.)" if c.get("reviews") else ""
        rating = f"{stars} {c['rating']}{rv}"
    else:
        rating = "☆ рейтинг уточняется"

    # цена (поле Чингиза — часто пусто на старте)
    if c.get("price_min") or c.get("price_max"):
        pm, px = c.get("price_min"), c.get("price_max")
        if pm and px:
            price = f"💰 {pm:,} – {px:,} ₸/мес".replace(",", " ")
        else:
            price = f"💰 от {(pm or px):,} ₸/мес".replace(",", " ")
    else:
        price = "💰 цена уточняется"

    lines = [
        f"🏫 *{c['name']}*",
        f"{c['cat_label']} · {c['subcat']}",
        status,
        "",
        rating,
        price,
        f"📍 {c['address']}, {DISTRICTS.get(c['dist_key'], '')[2:].strip()}",
    ]
    if c.get("schedule"):
        lines.append(f"🕐 {c['schedule']}")
    if c.get("age_from") and c.get("age_to"):
        lines.append(f"👦 {c['age_from']}–{c['age_to']} лет")
    if c.get("group_size"):
        lines.append(f"👥 {c['group_size']}")
    if str(c.get("trial", "")).lower() == "да":
        lines.append("🎟 Есть пробное занятие")
    if c.get("discount"):
        lines.append(f"🎉 {c['discount']}")
    if idx is not None and total:
        lines.append("")
        lines.append(f"🔎 {idx + 1} из {total}")
    return "\n".join(lines)
